config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  devise_for :users

  resources :users, only: [:show] do
    resources :items, only: [:create]
  end

  delete 'items/:id', to: 'items#delete', as: 'item'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if current_user
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      redirect_back(fallback_location: root_path)
    else
      flash[:alert] = "Item failed to save."
      redirect_back(fallback_location: root_path)
    end
  end

  def delete
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "#{@item.name} removed."
    else
      flash[:alert] = "Error deleting #{@item.name}"
    end
    redirect_to root_path
  end

  private
    def item_params
      params.require(:item).permit(:name, :user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    unless current_user
      redirect_to root_path
    end
    @user = current_user
    @items = @user.items
    @item = Item.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/show.html.erb
<h1>Welcome to the ToDo app.</h1>
<h3>You must create an account to get started!</h3>

app/views/items/_form.html.erb
<%= form_for @item, url: user_items_path(@user,@item), remote: true, method: :post, html: {class: "form-inline"} do |f| %>
  <div class="form-group">
    <%= f.text_field :name, placeholder: "Enter new ToDo", class: 'form-control' %>
  </div>

  <%= f.submit "Add", class: 'btn btn-primary mb-2' %>

<% end %>

app/views/items/_item.html.erb
<li class="list-group-item">
  <b><%= item.name %></b>
  <small class="text-muted">
    <%= distance_of_time_in_words Time.now, item.created_at + 7.days, include_seconds: true %> left
  </small>
  <%= link_to "", item, remote: true, method: :delete, class: 'glyphicon glyphicon-ok pull-right' %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <p class="navbar-brand"><%= link_to 'ToDo', root_path %></p>
        <span class="navbar-text navbar-right">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %></strong> |
            <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path,
            method: :delete, :class => 'navbar-link' %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
          <% end %>
      </div>
    </div>
    <div class="container">
      <% if flash[:notice] %>
        <div class="container">
          <div class="alert alert-info data-dismissible show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= flash[:notice] %>
          </div>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger data-dismissible show" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/show.html.erb
<div class="container">
  <h1><em><%= @user.email %></em></h1>
  <div class="col-md-6">
    <ul class="list-group list-group-flush">
      <%= render(partial: 'items/item', collection: @items) || "You have no ToDos." %>
    </ul>
  </div>
  <div class="container">
    <%= render partial: 'items/form' %>
  </div>
</div>